"""empty message

Revision ID: 2b25df0763a3
Revises: ad251af36185
Create Date: 2021-01-27 16:35:23.864311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b25df0763a3'
down_revision = 'ad251af36185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'story', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.alter_column('story', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
